### PR TITLE
Add input validation to the instance controller.

### PR DESCRIPTION
**Pull request by gijskant**

### CODE REVIEW

**Comment by gijskant** [comment]
I added tests because of the missing coverage and found out that POST returns 200 on success. Is it okay to change it to 201?

**Comment by ewelinagr** [comment]
@Gijs I already changed it, but my changes are conflicting with your PR, so will push it after your merge.

**Comment by ewelinagr** [comment]
I also have more tests for the controller in my upcoming commits.

**Comment by gijs** [comment]
o hai ;)

**Comment by gijskant** [comment]
On Slack that works

**Pull request merged**
